export const BEAUTY_PRESETS = [
  {
    id: "natural",
    name: "Natural",
    guestVisible: true,
    default: true,
    icon: "✨",
    css: "brightness(1.03)",
    beauty: {
      skinSmooth: 0,
      blemish: 6,
      teeth: 10,
      underEye: 4,
      shine: 6,
      tone: 6,
    },
    lighting: {
      exposure: 0,
      contrast: 5,
      warmth: 5,
      vibrance: 8,
      highlights: -10,
      shadows: 8,
      sharpness: 12,
    },
  },
  {
    id: "soft",
    name: "Soft",
    guestVisible: true,
    default: false,
    icon: "🌸",
    css: "brightness(1.04) contrast(0.96) saturate(1.02)",
    beauty: {
      skinSmooth: 0,
      blemish: 10,
      teeth: 12,
      underEye: 8,
      shine: 8,
      tone: 8,
    },
    lighting: {
      exposure: 2,
      contrast: -4,
      warmth: 4,
      vibrance: 6,
      highlights: -12,
      shadows: 10,
      sharpness: 8,
    },
  },
  {
    id: "bright",
    name: "Bright",
    guestVisible: true,
    default: false,
    icon: "☀️",
    css: "brightness(1.2) contrast(1.04) saturate(1.06)",
    beauty: {
      skinSmooth: 0,
      blemish: 8,
      teeth: 28,
      underEye: 8,
      shine: 6,
      tone: 6,
    },
    lighting: {
      exposure: 10,
      contrast: 4,
      warmth: 3,
      vibrance: 8,
      highlights: -8,
      shadows: 12,
      sharpness: 10,
    },
  },
  {
    id: "clean",
    name: "Clean",
    guestVisible: true,
    default: false,
    icon: "🔳",
    css: "brightness(0.96) contrast(1.08) saturate(1.08)",
    beauty: {
      skinSmooth: 0,
      blemish: 8,
      teeth: 8,
      underEye: 4,
      shine: 8,
      tone: 6,
    },
    lighting: {
      exposure: -2,
      contrast: 8,
      warmth: 0,
      vibrance: 8,
      highlights: -10,
      shadows: 6,
      sharpness: 12,
    },
  },
  {
    id: "bw",
    name: "B&W",
    guestVisible: true,
    default: false,
    icon: "🖤",
    css: "grayscale(1) contrast(1.06)",
    beauty: {
      skinSmooth: 0,
      blemish: 6,
      teeth: 0,
      underEye: 4,
      shine: 6,
      tone: 0,
    },
    lighting: {
      exposure: 0,
      contrast: 6,
      warmth: 0,
      vibrance: 0,
      highlights: -8,
      shadows: 8,
      sharpness: 10,
    },
  },
];

export function getGuestVisibleBeautyPresets() {
  return BEAUTY_PRESETS.filter((preset) => preset.guestVisible);
}

export function getDefaultBeautyPreset() {
  return BEAUTY_PRESETS.find((preset) => preset.default) || BEAUTY_PRESETS[0];
}
