export const BEAUTY_PRESETS = [
  {
    id: "natural",
    name: "Natural",
    guestVisible: true,
    default: true,
    icon: "✨",
    css: "brightness(1.03) contrast(1.02) saturate(1.03)",
    beauty: {
      skinSmooth: 0,
      blemish: 6,
      teeth: 10,
      underEye: 4,
      shine: 6,
      tone: 6,
    },
    lighting: {
      exposure: 0,
      contrast: 5,
      warmth: 5,
      vibrance: 8,
      highlights: -10,
      shadows: 8,
      sharpness: 12,
    },
  },
  {
    id: "soft",
    name: "Soft Glow",
    guestVisible: true,
    default: false,
    icon: "🌸",
    css: "brightness(1.07) contrast(0.97) saturate(1.045)",
    beauty: {
      skinSmooth: 10,
      blemish: 10,
      teeth: 16,
      underEye: 8,
      shine: 10,
      tone: 12,
    },
    lighting: {
      exposure: 2,
      contrast: -4,
      warmth: 4,
      vibrance: 6,
      highlights: -12,
      shadows: 10,
      sharpness: 8,
    },
  },
  {
    id: "golden",
    name: "Golden Hour",
    guestVisible: true,
    default: false,
    icon: "☀️",
    css: "brightness(1.1) contrast(1.03) saturate(1.11) sepia(0.06)",
    beauty: {
      skinSmooth: 6,
      blemish: 10,
      teeth: 28,
      underEye: 8,
      shine: 10,
      tone: 18,
    },
    lighting: {
      exposure: 10,
      contrast: 4,
      warmth: 3,
      vibrance: 8,
      highlights: -8,
      shadows: 12,
      sharpness: 10,
    },
  },
  {
    id: "vivid",
    name: "Vivid",
    guestVisible: true,
    default: false,
    icon: "💎",
    css: "brightness(1.015) contrast(1.11) saturate(1.16)",
    beauty: {
      skinSmooth: 4,
      blemish: 8,
      teeth: 10,
      underEye: 6,
      shine: 6,
      tone: 7,
    },
    lighting: {
      exposure: -2,
      contrast: 8,
      warmth: 0,
      vibrance: 8,
      highlights: -10,
      shadows: 6,
      sharpness: 12,
    },
  },
  {
    id: "bw",
    name: "Mono",
    guestVisible: true,
    default: false,
    icon: "🖤",
    css: "grayscale(1) contrast(1.12) brightness(1.025)",
    beauty: {
      skinSmooth: 3,
      blemish: 6,
      teeth: 0,
      underEye: 4,
      shine: 6,
      tone: 0,
    },
    lighting: {
      exposure: 0,
      contrast: 6,
      warmth: 0,
      vibrance: 0,
      highlights: -8,
      shadows: 8,
      sharpness: 10,
    },
  },
  {
    id: "infernal-toon",
    name: "Infernal Toon",
    guestVisible: true,
    default: false,
    icon: "😈",
    css: "brightness(1.01) contrast(1.12) saturate(1.08)",
    cloudinaryTransformation: "e_cartoonify",
    beauty: {
      skinSmooth: 7,
      blemish: 8,
      teeth: 8,
      underEye: 5,
      shine: 4,
      tone: 14,
    },
    lighting: {
      exposure: -2,
      contrast: 10,
      warmth: 0,
      vibrance: 10,
      highlights: -10,
      shadows: 5,
      sharpness: 18,
    },
    cartoon: {
      enabled: true,
      deliveryOnly: true,
      levels: 10,
      edgeThreshold: 78,
    },
  },
];

export function getGuestVisibleBeautyPresets() {
  return BEAUTY_PRESETS.filter((preset) => preset.guestVisible);
}

export function getDefaultBeautyPreset() {
  return BEAUTY_PRESETS.find((preset) => preset.default) || BEAUTY_PRESETS[0];
}
